##Application Name to appear in Azure App Insights
spring:
  application:
    name: deliverySchedule-crudService-mongoApi
  ##Properties for Mongo
  data:
    mongodb:
      database: deliverymoment-db
      uri: mongodb://delivery-schedule-mongo-api:mKlL18atKscp64mmnhZ5KtzTZqVNTerJQfQIhgMJKXHnF8ezWD8yjPnIc8iRjhQpv5UjTriBZKnF3yotVVaEgw==@delivery-schedule-mongo-api.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@delivery-schedule-mongo-api@
server:
  port: 8092
  application:
    name: deliverySchedule-crudService-mongoApi
##Properties for Prometheus End Points
endpoints:
  prometheus:
    enabled: true
management:
  endpoints:
    web:
      base-path: "/servicetemplate/api/v1/service-template"
      exposure:
        include: "*"
##OpenAPI To Enable
springdoc:
  swagger-ui.path: "/servicetemplate/api/v1/service-template/swagger-ui-custom.html"
  api-docs.path: "/servicetemplate/api/v1/store-cluster-service/api-docs"
##Azure Cosmos Credentials and App Insights Key
azure:
  application-insights:
    instrumentation-key: f0807cb4-14fe-437c-ab41-6ed885735d2b

service:
  perf-urls:
    get-model-url: "http://localhost:8097/servicetemplate/api/v1/getModel"
  test-data:
    id: "1"
